services:
  - type: web
    name: flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn --timeout 120 --workers 2 --bind 0.0.0.0:$PORT Server:app  # Bind to PORT env var
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
